#ifndef MULTIPORT_NETWORK_SETTINGS_H
#define MULTIPORT_NETWORK_SETTINGS_H


#define PORT_NUM 1
#define THREAD_NUM PORT_NUM

#define PORT_BASE 8033

#define INIT_READ_BUF_SIZE 1000

#define MAX_CONN 1024

#define ROUND_NUM 20

#define TEST_WORK_STEP_SIZE 130

#endif //MULTIPORT_NETWORK_SETTINGS_H
