#ifndef MULTIPORT_NETWORK_SETTINGS_H
#define MULTIPORT_NETWORK_SETTINGS_H


#define PORT_NUM 4
#define THREAD_NUM PORT_NUM

#define PORT_BASE 8033

#define INIT_RBUF_SIZE 100

#define ROUND_NUM 5


#endif //MULTIPORT_NETWORK_SETTINGS_H
